# Generated by Django 3.1.5 on 2021-01-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('total_cases', models.IntegerField()),
                ('total_deaths', models.IntegerField()),
            ],
        ),
    ]
