# Generated by Django 3.1.5 on 2021-03-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid19',
            name='Latitude',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='covid19',
            name='Longitude',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='covid19',
            name='aged_70_older',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='covid19',
            name='cardiovasc_death_rate',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='covid19',
            name='diabetes_prevalence',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='covid19',
            name='extreme_poverty',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='covid19',
            name='female_smokers',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='covid19',
            name='gdp_per_capita',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='covid19',
            name='handwashing_facilities',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='covid19',
            name='hosp_patients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='covid19',
            name='hospital_beds_per_thousand',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='covid19',
            name='human_development_index',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='covid19',
            name='icu_patients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='covid19',
            name='life_expectancy',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='covid19',
            name='male_smokers',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='covid19',
            name='median_age',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='covid19',
            name='people_fully_vaccinated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='covid19',
            name='people_vaccinated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='covid19',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='covid19',
            name='population_density',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='covid19',
            name='reproduction_rate',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='covid19',
            name='stringency_index',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='covid19',
            name='total_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='covid19',
            name='total_vaccinations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='covid19',
            name='weekly_hosp_admissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='covid19',
            name='weekly_icu_admissions',
            field=models.IntegerField(default=0),
        ),
    ]
