# Generated by Django 3.1.5 on 2021-03-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0004_auto_20210317_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covid19',
            name='extreme_poverty',
        ),
        migrations.RemoveField(
            model_name='covid19',
            name='female_smokers',
        ),
        migrations.RemoveField(
            model_name='covid19',
            name='human_development_index',
        ),
        migrations.RemoveField(
            model_name='covid19',
            name='life_expectancy',
        ),
        migrations.RemoveField(
            model_name='covid19',
            name='male_smokers',
        ),
        migrations.RemoveField(
            model_name='covid19',
            name='median_age',
        ),
        migrations.RemoveField(
            model_name='covid19',
            name='people_fully_vaccinated',
        ),
        migrations.RemoveField(
            model_name='covid19',
            name='population',
        ),
        migrations.RemoveField(
            model_name='covid19',
            name='population_density',
        ),
        migrations.RemoveField(
            model_name='covid19',
            name='weekly_hosp_admissions',
        ),
        migrations.RemoveField(
            model_name='covid19',
            name='weekly_icu_admissions',
        ),
    ]
