# Generated by Django 3.1.5 on 2021-03-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0005_auto_20210317_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid19',
            name='aged_65_older',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='covid19',
            name='aged_70_older',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='covid19',
            name='cardiovasc_death_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='covid19',
            name='diabetes_prevalence',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='covid19',
            name='gdp_per_capita',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='covid19',
            name='handwashing_facilities',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='covid19',
            name='hospital_beds_per_thousand',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='covid19',
            name='reproduction_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='covid19',
            name='stringency_index',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
